apiVersion: networksecurity.googleapis.com/v1
kind: AuthzPolicy
metadata:
  name: enterprise-token-injector-policy
  namespace: us-central1
spec:
  action: CUSTOM
  policyProfile: REQUEST_AUTHZ
  customProvider:
    authzExtension:
      resources:
        - "projects/${PROJECT_NUMBER}/locations/us-central1/authzExtensions/enterprise-extproc-ext"
  target:
    resources:
      - "projects/${PROJECT_NUMBER}/locations/us-central1/agentGateways/${AGENT_GATEWAY_NAME}"
  httpRules:
    - to:
        operations:
          - paths:
              - prefix: /
