apiVersion: networkservices.googleapis.com/v1
kind: AuthzExtension
metadata:
  name: enterprise-extproc-ext
  namespace: us-central1
spec:
  service: "enterprise-extproc-4r5j2evtkq-uc.a.run.app"
  authority: "enterprise-extproc-4r5j2evtkq-uc.a.run.app"
  timeout: 1.5s
